addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - $HOME/.npm
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - 12
  - 10
  - 8
script: "./coverage.sh"
sudo: false
